/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardStaticBadChapter: typeof import('./src/@core/components/cards/CardStaticBadChapter.vue')['default']
    CardStaticBadStudent: typeof import('./src/@core/components/cards/CardStaticBadStudent.vue')['default']
    CardStaticTopChapter: typeof import('./src/@core/components/cards/CardStaticTopChapter.vue')['default']
    CardStaticTopChaptert: typeof import('./src/@core/components/cards/CardStaticTopChaptert.vue')['default']
    CardStaticTopStudent: typeof import('./src/@core/components/cards/CardStaticTopStudent.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
  }
}
